In [1]:
# so kernel doesn't have to be restarted
%load_ext autoreload
%autoreload 2

# helper scripts
from knn_helper import *
import pandas as pd

/scratch/users/zachrewolinski/conda/envs/mdi/lib/python3.10/site-packages/glmnet/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/scratch/users/zachrewolinski/conda/envs/mdi/lib/python3.10/site-packages/pkg_resources/__init__.py:3146: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/scratch/users/zachrewolinski/conda/envs/mdi/lib/python3.10/site-packages/pkg_resources/__init__.py:3146: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits.basemap_data')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/scratch/users/zachrewolinski/conda/envs/mdi/lib/python3.10/site-packages/pkg_resources/__init__.py:2558: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(parent)
/scratch/users/zachrewolinski/conda/envs/mdi/lib/python3.10/site-packages/pkg_resources/__init__.py:3146: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits.basemap_data')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/scratch/users/zachrewolinski/conda/envs/mdi/lib/python3.10/site-packages/pkg_resources/__init__.py:3146: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)

# Random Forest Results

In [ ]:
### RANDOM FOREST RESULTS
over_shap = []
over_lime = []
over_lmdi_sutera = []
means_lst = []
medians_lst = []
labels = "preds"
k = 1
nbr_dist = "l1"
cfact_dist = "l1"
names = ['Spam', 'Ozone', 'Pol', 'House 16H', 'Higgs', 'Jannis']
counter = 0
for data_id in [43, 9978, 361062, 361063, 361069, 361071]:
    shap_distances = np.loadtxt(f"results/rf/openml_{data_id}/shap/{labels}/k{k}/nbr-dist-{nbr_dist}_cfact-dist-{cfact_dist}.csv", delimiter=",")
    lime_distances = np.loadtxt(f"results/rf/openml_{data_id}/lime/{labels}/k{k}/nbr-dist-{nbr_dist}_cfact-dist-{cfact_dist}.csv", delimiter=",")
    lmdi_sutera_distances = np.loadtxt(f"results/rf/openml_{data_id}/lmdi/{labels}/k{k}/nbr-dist-{nbr_dist}_cfact-dist-{cfact_dist}.csv", delimiter=",")
    lmdi_plus_distances = np.loadtxt(f"results/rf/openml_{data_id}/lmdi_plus/{labels}/k{k}/nbr-dist-{nbr_dist}_cfact-dist-{cfact_dist}.csv", delimiter=",")
    # get means and medians of each:
    means = {
        "shap": np.mean(shap_distances),
        "lime": np.mean(lime_distances),
        "lmdi_sutera": np.mean(lmdi_sutera_distances),
        "lmdi+": np.mean(lmdi_plus_distances),
    }
    medians = {
        "shap": np.median(shap_distances),
        "lime": np.median(lime_distances),
        "lmdi_sutera": np.median(lmdi_sutera_distances),
        "lmdi+": np.median(lmdi_plus_distances),
    }
    
    means_lst.append({names[counter]: means})
    medians_lst.append({names[counter]: medians})
    counter += 1
    
    over_shap.append(means["shap"]-means["lmdi+"])
    over_lime.append(means["lime"]-means["lmdi+"])
    over_lmdi_sutera.append(means["lmdi_sutera"]-means["lmdi+"])

In [3]:
print("# of Losses:", sum(np.array([sum(np.array(over_shap) < 0),
                                    sum(np.array(over_lime) < 0),
                                    sum(np.array(over_lmdi_sutera) < 0)])))

# of Losses: 0

In [14]:
# make medians_lst a dataframe with columns being datasets and rows being methods
medians_df = pd.DataFrame({list(d.keys())[0]: list(d.values())[0] for d in medians_lst})
# reorder df rows
medians_df = medians_df.reindex(['lmdi+', 'lime', 'shap', 'lmdi_sutera'])
# rename df row names
medians_df.index = ['LMDI+', 'LIME', 'TreeSHAP', 'Local MDI']
# reorder df columns
medians_df = medians_df[['House 16H', 'Higgs', 'Pol', 'Ozone', 'Jannis', 'Spam']]
medians_df

           House 16H      Higgs        Pol      Ozone     Jannis       Spam
LMDI+       6.530280  17.694568   7.657638  31.974321  39.964031  12.780391
LIME        8.027789  19.178099   9.370878  34.205151  44.421518  16.410204
TreeSHAP    8.045210  19.960932   9.481639  43.749718  43.501792  16.484652
Local MDI  11.473445  21.967686  10.750003  36.958241  47.251987  17.843236

In [15]:
# make means_lst a dataframe with columns being datasets and rows being methods
means_df = pd.DataFrame({list(d.keys())[0]: list(d.values())[0] for d in means_lst})
# reorder df rows
means_df = means_df.reindex(['lmdi+', 'lime', 'shap', 'lmdi_sutera'])
# rename df row names
means_df.index = ['LMDI+', 'LIME', 'TreeSHAP', 'Local MDI']
# reorder df columns
means_df = means_df[['House 16H', 'Higgs', 'Pol', 'Ozone', 'Jannis', 'Spam']]
means_df

           House 16H      Higgs        Pol      Ozone     Jannis       Spam
LMDI+       7.649203  18.247936   9.086941  34.694681  40.395984  15.194992
LIME        9.503305  19.901391  11.357722  36.343563  44.681014  18.661235
TreeSHAP    9.496799  20.618358  10.868890  44.343489  44.287463  19.796848
Local MDI  12.748603  22.795109  11.150972  39.016900  48.058515  21.118984

# Random Forest Results

In [17]:
### GRADIENT BOOSTING RESULTS
over_shap = []
over_lime = []
means_lst = []
medians_lst = []
labels = "preds"
k = 1
nbr_dist = "l1"
cfact_dist = "l1"
names = ['Spam', 'Ozone', 'Pol', 'House 16H', 'Higgs', 'Jannis']
counter = 0
for data_id in [43, 9978, 361062, 361063, 361069, 361071]:
    shap_distances = np.loadtxt(f"results/gb/openml_{data_id}/shap/{labels}/k{k}/nbr-dist-{nbr_dist}_cfact-dist-{cfact_dist}.csv", delimiter=",")
    lime_distances = np.loadtxt(f"results/gb/openml_{data_id}/lime/{labels}/k{k}/nbr-dist-{nbr_dist}_cfact-dist-{cfact_dist}.csv", delimiter=",")
    lmdi_plus_distances = np.loadtxt(f"results/gb/openml_{data_id}/lmdi_plus/{labels}/k{k}/nbr-dist-{nbr_dist}_cfact-dist-{cfact_dist}.csv", delimiter=",")
    # get means and medians of each:
    means = {
        "shap": np.mean(shap_distances),
        "lime": np.mean(lime_distances),
        "lmdi+": np.mean(lmdi_plus_distances),
    }
    medians = {
        "shap": np.median(shap_distances),
        "lime": np.median(lime_distances),
        "lmdi+": np.median(lmdi_plus_distances),
    }
    
    means_lst.append({names[counter]: means})
    medians_lst.append({names[counter]: medians})
    counter += 1
    
    over_shap.append(means["shap"]-means["lmdi+"])
    over_lime.append(means["lime"]-means["lmdi+"])

In [18]:
print("# of Losses:", sum(np.array([sum(np.array(over_shap) < 0),
                                    sum(np.array(over_lime) < 0)])))

# of Losses: 0

In [19]:
# make medians_lst a dataframe with columns being datasets and rows being methods
medians_df = pd.DataFrame({list(d.keys())[0]: list(d.values())[0] for d in medians_lst})
# reorder df rows
medians_df = medians_df.reindex(['lmdi+', 'lime', 'shap'])
# rename df row names
medians_df.index = ['LMDI+', 'LIME', 'TreeSHAP']
# reorder df columns
medians_df = medians_df[['House 16H', 'Higgs', 'Pol', 'Ozone', 'Jannis', 'Spam']]
medians_df

          House 16H      Higgs        Pol      Ozone     Jannis       Spam
LMDI+      5.737791  17.838713   6.034750  31.861186  41.334131  11.467630
LIME       8.123942  19.055273  10.038613  36.865215  45.176987  21.916890
TreeSHAP   7.099951  18.482246   8.522499  34.352284  43.865658  14.098376

In [20]:
# make means_lst a dataframe with columns being datasets and rows being methods
means_df = pd.DataFrame({list(d.keys())[0]: list(d.values())[0] for d in means_lst})
# reorder df rows
means_df = means_df.reindex(['lmdi+', 'lime', 'shap'])
# rename df row names
means_df.index = ['LMDI+', 'LIME', 'TreeSHAP']
# reorder df columns
means_df = means_df[['House 16H', 'Higgs', 'Pol', 'Ozone', 'Jannis', 'Spam']]
means_df

          House 16H      Higgs        Pol      Ozone     Jannis       Spam
LMDI+      6.800225  18.470154   7.698557  34.321992  41.848724  13.384658
LIME       9.605768  20.027935  12.005236  40.992963  45.639559  24.332827
TreeSHAP   8.468283  19.170825  10.173399  37.364389  43.812058  16.352601