In [3]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
import statsmodels.api as sm
from scipy import stats
import sys
import shap
import methods
from methods import lin_reg_t_test, tree_mdi, perm_importance, knockpy_swap_integral, tree_shap_mean

In [4]:
diabetes = datasets.load_diabetes()
X = diabetes.data
y = diabetes.target

In [5]:
#X = pd.DataFrame(data=X, columns=['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10'])
lin_reg = sm.OLS(y, X)
lin_reg_fit = lin_reg.fit()
print(lin_reg_fit.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.106
Model:                            OLS   Adj. R-squared (uncentered):              0.085
Method:                 Least Squares   F-statistic:                              5.100
Date:                Thu, 24 Feb 2022   Prob (F-statistic):                    4.72e-07
Time:                        09:30:50   Log-Likelihood:                         -2873.9
No. Observations:                 442   AIC:                                      5768.
Df Residuals:                     432   BIC:                                      5809.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           -10.0122    179.967     -0.056      0.956    -363.731     343.707
x2          -239.8191    184.404     -1.301      0.194    -602.259     122.621
x3           519.8398    200.401      2.594      0.010     125.957     913.723
x4           324.3904    197.053      1.646      0.100     -62.912     711.692
x5          -792.1842   1255.066     -0.631      0.528   -3258.979    1674.611
x6           476.7458   1021.183      0.467      0.641   -1530.360    2483.851
x7           101.0446    640.155      0.158      0.875   -1157.162    1359.251
x8           177.0642    486.370      0.364      0.716    -778.882    1133.010
x9           751.2793    517.774      1.451      0.148    -266.391    1768.950
x10           67.6254    198.747      0.340      0.734    -323.005     458.256
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   0.223
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         21.7
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [6]:
results = lin_reg_t_test(X,y,lin_reg_fit)
results

   Var  Importance
0    0    0.955659
1    1    0.194119
2    2    0.009809
3    3    0.100448
4    4    0.528251
5    5    0.640838
6    6    0.874654
7    7    0.715997
8    8    0.147512
9    9    0.733827

In [7]:
decision_tree = DecisionTreeRegressor(random_state=0)
decision_tree_fit = decision_tree.fit(X, y)

random_forest = RandomForestClassifier(random_state=0)
random_forest_fit = random_forest.fit(X, y)

In [8]:
results = tree_mdi(X,y,decision_tree_fit)
results

   Var  Importance
0    0    0.046088
1    1    0.009412
2    2    0.233386
3    3    0.075490
4    4    0.069857
5    5    0.069513
6    6    0.071462
7    7    0.013112
8    8    0.347962
9    9    0.063718

In [9]:
results = tree_mdi(X,y,random_forest_fit)
results

   Var  Importance
0    0    0.108655
1    1    0.026756
2    2    0.123988
3    3    0.111157
4    4    0.111698
5    5    0.117195
6    6    0.110542
7    7    0.061189
8    8    0.119919
9    9    0.108900

In [10]:
results = perm_importance(X,y,decision_tree_fit)
results

   Var  Importance
0    0    0.142999
1    1    0.135123
2    2    1.022482
3    3    0.414241
4    4    0.253593
5    5    0.261534
6    6    0.330689
7    7    0.032236
8    8    0.906423
9    9    0.242232

In [12]:
results = knockpy_swap_integral(X,y,decision_tree)
results

	---------------------------------------------------------
	---------------------------------------------------------
	The choldate package is not installed:
	solving for MVR or maxent knockoffs without it will be
	~5x slower. For instructions on how to install choldate,
	see https://amspector100.github.io/knockpy/installation.html.
	To disable this warning, set choldate_warning=False as an
	argument or a knockoff_kwarg.
	----------------------------------------------------------
	----------------------------------------------------------

Treating y data as continuous even though it may be discrete.

   Var  Rejected
0    0       0.0
1    1       0.0
2    2       0.0
3    3       0.0
4    4       0.0
5    5       0.0
6    6       0.0
7    7       0.0
8    8       0.0
9    9       0.0

In [ ]:
X, y = shap.datasets.boston()
results = tree_shap_mean(X,y,decision_tree_fit)